name: Initialize Repository

on:
  push:
    paths:
      - package.json  # Trigger only when package.json is added or updated

jobs:
  initialize-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name : Pull latest changes
        run: | 
         git pull origin $(git rev-parse --abbrev-ref HEAD) --rebase
      - name: Check if package.json has been processed
        run: |
          if [ -f ".github/.initialized" ]; then
            echo "The repository has already been initialized."
            exit 1
          fi

      - name: Replace {{repo_name}} in package.json
        env:
          REPO_NAME: ${{ github.repository }}
        run: |
          sed -i "s/{{repo_name}}/${REPO_NAME##*/}/g" package.json      
      - name: Create flag file to mark initialization
        run: |
          mkdir -p .github
          echo "Initialized" > .github/.initialized

      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git add package.json .github/.initialized
          git commit -m "Initialize repository with repo name"
          git push origin $(git rev-parse --abbrev-ref HEAD)
